version: "3.4"

services:

  ospl-daemon1:
    image: ts-dockerhub.lsst.org/ospl-daemon:c0013
    container_name: ospl-daemon
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.120"

  ospl-daemon2:
    image: ts-dockerhub.lsst.org/ospl-daemon:c0013
    container_name: ospl-daemon
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.121"

  ospl-daemon3:
    image: ts-dockerhub.lsst.org/ospl-daemon:c0013
    container_name: ospl-daemon
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.122"

networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
