version: "3.4"

services:

  firefly:
    image: ipac/firefly:lsst-dev
    container_name: lab_jupyter_servers_firefly
    environment:
      - ADMIN_PASSWORD=saluser
      - MANAGER=FALSE
      - FIREFLY_OPTS="-Dvisualize.fits.search.path=/scratch/firefly"
      - FIREFLY_SHARED_WORK_DIR="/scratch/firefly/workarea"
      - MAX_JVM_SIZE=64G
      - DEBUG=false
    volumes:
      - /scratch
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.230"

  mreuter:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag02
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_mreuter:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag02_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag02_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.204"

  patrickingraham:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag03
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_pingraham:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag03_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag03_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.219"

  ecoughlin:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag04
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_ecoughlin:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag04_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag04_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.220"

  tribeiro:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag05
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_tribeiro:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag05_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag05_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.221"

  SashaBrownsberger:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag06
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_sasha:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag06_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag06_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.222"

  mondrik:
    image: lsstts/develop-env:salobj4_b30
    container_name: atdiag07
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_mondrik:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag07_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag07_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.223"


networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
