version: "3.4"

services:

  patrickingraham:
    image: lsstts/develop-env:latest
    container_name: atdiag03
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_pingraham:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag03_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag03_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.219"

  ecoughlin:
    image: lsstts/develop-env:latest
    container_name: atdiag04
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_ecoughlin:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag04_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag04_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.220"

  tribeiro:
    image: lsstts/develop-env:latest
    container_name: atdiag05
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/saluser/ingest/
      - /home/saluser/develop_tribeiro:/home/saluser/develop
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./atdiag05_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./atdiag05_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.221"

networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
