FROM lsstts/develop-env:develop

#WORKDIR /home/saluser/repos/ts_scriptqueue
#RUN git fetch && git checkout "tags/v1.4.1" -b "v1.4.1"

##RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
#    source /home/saluser/repos/ts_sal/setup.env && \
#    setup ts_sal -t current && \
#    setup ts_salobj -t current && \
#    setup ts_scriptqueue -t current && \
#    scons

WORKDIR /home/saluser/
