version: "3.4"

services:

  queue:
    image: lsstts/develop-env:salobj4_b30
    container_name: queue
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/develop:/home/saluser/develop
      - ./queue_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.201"

  script:
    image: lsstts/develop-env:salobj4_b30
    container_name: script
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/develop:/home/saluser/develop
      - ./request_script_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.202"

  ingester:
    image: lsstsqre/centos:7-stack-lsst_distrib-w_2019_25
    container_name: ingester
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/lsst/ingest/
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./ingester_setup.sh:/home/lsst/.setup.sh
    stdin_open: true
    tty: true
    entrypoint: ["/home/lsst/.setup.sh"]

networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
