version: "3.4"

services:

  queue:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: queue
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/develop:/home/saluser/develop
      - ./queue_setup.sh:/home/saluser/.setup.sh
#      - ./ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.201"

  script:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: script
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/develop:/home/saluser/develop
      - ./request_script_setup.sh:/home/saluser/.setup.sh
#      - ./ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.202"

  atspectrograph:
    image: lsstts/atspectrograph:DM-22016_salobj5
    container_name: atspec
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.206"

  watcher:
    image: lsstts/watcher:v0.2.1_salobj5
    container_name: watcher
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
#    volumes:
#      - ./ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.224"

  ingester:
    image: lsstsqre/centos:7-stack-lsst_distrib-w_2019_44
    container_name: ingester
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - /home/saluser/ingest/:/home/lsst/ingest/
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./ingester_setup.sh:/home/lsst/.setup.sh
    stdin_open: true
    tty: true
    entrypoint: ["/home/lsst/.setup.sh"]

  atmcs-sim:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - ./atmcs_sim_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.216"

  atdome-sim:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: atdome-sim
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - ./atdome_sim_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.214"

  atdometrajectory:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: atdometrajectory
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    volumes:
      - ./atdometrajectory_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.215"

  atpneumatics-sim:
    image: lsstts/at_pneumatics_sim:DM-22016_salobj5
    container_name: atpneumatics-sim
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.217"

  ataos:
    image: lsstts/ataos:DM-22130_salobj5
    container_name: ataos
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.208"

  atptg:
    image: tiagorib/ptkernel:DM-22130_xml4.4.1_sal4.0.0
    container_name: atptg
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
      - TELESCOPE=AuxTel
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.218"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  athexapod:
    image: lsstts/ts_athexapod:v0.2.0_sal_v4.0.0_salobj_v5.0.0
    container_name: athexapod
    volumes:
      - ./hexapod_tcpConfiguration.yaml:/home/saluser/repos/ts_salobjATHexapod/bin/settingFiles/Test/1/tcpConfiguration.yaml
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.155"
    depends_on:
      - hexapod-sim

  hexapod-sim:
    image: couger01/hexapod_simulator
    container_name: hexapod-sim
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.156"
    stdin_open: true
    tty: true

  mtptg:
    image: tiagorib/ptkernel:DM-22130_xml4.4.1_sal4.0.0
    container_name: mtptg
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
      - TELESCOPE=Main
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.21"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


  mt-rotator-sim:
    image: lsstts/rotator:v0.1.0_sim
    container_name: mt-rotator-sim
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.22"

  mt-cam-hexapod-sim:
    image: lsstts/hexapod:v0.4.0_b42
    container_name: mt-cam-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=citesttucson
      - HEXAPOD_ID=-s 1
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.36"

  mt-m2-hexapod-sim:
    image: lsstts/hexapod:v0.4.0_b42
    container_name: mt-m2-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=citesttucson
      - HEXAPOD_ID=-s 2
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.37"

  atmonochromator:
    image: lsstts/monochromator:v0.1.0_sal4.4.0_salobj3.11.1
    container_name: atmonochromator
    environment:
      - LSST_DDS_DOMAIN=auxtelpath
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "10.0.100.205"

networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
