version: '3.6'

services:

  salkafka_115:
    image: ts-dockerhub.lsst.org/salkafka:c0010
    depends_on:
      - ospl-daemon
    container_name: salkafka_115
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - BROKER_IP=lsst-kafka-0-nts-efd.ncsa.illinois.edu
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=ATHeaderService ATArchiver ATMonochromator ATSpectrograph Electrometer Test ScriptQueue Script ATDome ATDomeTrajectory ATAOS ATPneumatics Watcher ATHexapod ATPtg ATMCS ATCamera
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.115"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_116:
    image: ts-dockerhub.lsst.org/salkafka:c0010
    depends_on:
      - ospl-daemon
    container_name: salkafka_116
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - BROKER_IP=lsst-kafka-0-nts-efd.ncsa.illinois.edu
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=CCHeaderService CCArchiver CCCamera
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.116"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_117:
    image: ts-dockerhub.lsst.org/salkafka:c0010
    depends_on:
      - ospl-daemon
    container_name: salkafka_117
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - BROKER_IP=lsst-kafka-0-nts-efd.ncsa.illinois.edu
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=MTM1M3
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.117"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_118:
    image: ts-dockerhub.lsst.org/salkafka:c0010
    depends_on:
      - ospl-daemon
    container_name: salkafka_118
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - BROKER_IP=lsst-kafka-0-nts-efd.ncsa.illinois.edu
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=Rotator Hexapod MTM2 MTAOS MTPtg MTMount NewMTMount
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ../ospl-6.10.4-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.118"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
