version: '3.6'

services:

  salkafka_50:
    image: lsstts/salkafka:c0009
    container_name: salkafka_50
    environment:
      - LSST_DDS_DOMAIN=tucson
      - BROKER_IP=kafka-0-tucson-teststand-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-tucson-teststand-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=ATHeaderService ATArchiver ATMonochromator ATSpectrograph Electrometer Test ScriptQueue Script ATDome ATDomeTrajectory ATAOS ATPneumatics Watcher ATHexapod
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.50"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_51:
    image: lsstts/salkafka:c0009
    container_name: salkafka_51
    environment:
      - LSST_DDS_DOMAIN=tucson
      - BROKER_IP=kafka-0-tucson-teststand-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-tucson-teststand-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=ATPtg ATMCS ATCamera
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.51"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_52:
    image: lsstts/salkafka:c0009
    container_name: salkafka_52
    environment:
      - LSST_DDS_DOMAIN=tucson
      - BROKER_IP=kafka-0-tucson-teststand-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-tucson-teststand-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTM1M3
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.52"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka_53:
    image: lsstts/salkafka:c0009
    container_name: salkafka_53
    environment:
      - LSST_DDS_DOMAIN=tucson
      - BROKER_IP=kafka-0-tucson-teststand-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-tucson-teststand-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=CCCamera Rotator Hexapod MTM2 MTAOS MTPtg MTMount NewMTMount
    stdin_open: true
    tty: true
    networks:
      lab-priv-network:
        ipv4_address: "140.252.34.53"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
