version: '3.6'

services:

        salkafka:
                image: lsstts/salkafka:DM-20991
                container_name: salkafka
                environment:
                        - LSST_DDS_DOMAIN=auxtelpath
                        - BROKER_IP=140.252.32.142
                        - BROKER_PORT=31090
                        - REGISTRY_ADDR=https://test-registry-efd.lsst.codes
                        - LOG_LEVEL=10
                        - CSC_LIST=ATCamera ATHeaderService ATArchiver ATMonochromator ATSpectrograph Electrometer Test ScriptQueue Script ATPtg ATMCS ATDome ATDomeTrajectory ATPneumatics
                stdin_open: true
                tty: true
                volumes:
                        - ./ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
                networks:
                        bridge:
                        lab-priv-network:
                                ipv4_address: "10.0.100.150"

networks:
  default:
    external:
      name: lab-priv-network
  lab-priv-network:
    external: true
  bridge:
