FROM centos:7

ARG PYTHON_VERSION=3.7
ARG CONDA_VERSION=4.5.4
ARG SALOBJ_VERSION=5.0.0

ENV OSPL_HOME=/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux
ENV LSST_DDS_DOMAIN=citest
ENV PYTHON_BUILD_VERSION=${PYTHON_VERSION}
ENV PYTHON_BUILD_LOCATION=/home/saluser/miniconda3

USER root

RUN adduser -u 1004 -m -s /bin/bash saluser

COPY lsst-ts.repo /tmp/lsst-ts.repo

RUN cat /tmp/lsst-ts.repo >> /etc/yum.conf && \
    yum install -y wget \
                   git \
                   make \
                   gcc-c++ \
                   OpenSpliceDDS-6.9.0

USER saluser
WORKDIR /home/saluser

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && chmod +x miniconda.sh && ./miniconda.sh -b

RUN source ~/miniconda3/bin/activate && \
    conda config --add channels conda-forge && \
    conda install -c lsstts python=${PYTHON_VERSION} ts-dds ts-salobj=${SALOBJ_VERSION} cython

COPY setup.sh /home/saluser/.setup.sh

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/.setup.sh"]
