version: "3.4"

services:

  queue:
    image: lsstts/develop-env:b65
    container_name: queue
    environment:
      - LSST_DDS_DOMAIN=ncsa
    volumes:
      - /home/saluser/develop:/home/saluser/develop
      - ./queue_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.100"

  atmcs-sim:
    image: lsstts/atmcs_sim:v1.0.0_salobj_v5.10.0_xml_v5.0.0
    environment:
      - LSST_DDS_DOMAIN=ncsa
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.149"

  atdome-sim:
    image: lsstts/atdome:v1.1.1_salobj_v5.10.0_xml_v5.0.0
    container_name: atdome-sim
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - RUN_ARG=-s
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.148"

  atdometrajectory:
    image: lsstts/atdometrajectory:v1.3.1_salobj_v5.10.0_xml_v5.0.0
    container_name: atdometrajectory
    environment:
      - LSST_DDS_DOMAIN=ncsa
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.147"

  atpneumatics-sim:
    image: lsstts/at_pneumatics_sim:v0.5.0_salobj_v5.10.0_xml_v5.0.0
    container_name: atpneumatics-sim
    environment:
      - LSST_DDS_DOMAIN=ncsa
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.146"

  ataos:
    image: lsstts/ataos:v1.5.1_salobj_v5.10.0_xml_v5.0.0
    container_name: ataos
    environment:
      - LSST_DDS_DOMAIN=ncsa
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.145"

  atptg:
    image: ts-dockerhub.lsst.org/ptkernel:DM-24562
    container_name: atptg
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - TELESCOPE=AT
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.144"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  athexapod:
    image: lsstts/athexapod:v0.4.1_salobj_v5.10.0_xml_v5.0.0
    container_name: athexapod
    environment:
      - LSST_DDS_DOMAIN=ncsa
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.143"
    depends_on:
      - hexapod-sim

  hexapod-sim:
    image: ts-dockerhub.lsst.org/hexapod_simulator
    container_name: hexapod-sim
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.142"
    stdin_open: true
    tty: true

  atspectrograph:
    image: lsstts/atspec:v0.5.1_salobj_v5.10.0_xml_v5.0.0
    container_name: atspec
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - RUN_ARG=-s
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.140"


networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
