version: "3.4"

services:

  mtqueue:
    image: ts-dockerhub.lsst.org/scriptqueue:${CYCLE}
    container_name: mtqueue
    environment:
      - LSST_DDS_PARTITION_PREFIX=ncsa
      - RUN_ARG=1
      - OSPL_INFOFILE=/tmp/ospl-info-mtqueue.log
      - OSPL_ERRORFILE=/tmp/ospl-error-mtqueue.log
    volumes:
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /tmp/docker_tmp/:/tmp/
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.127"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  atqueue:
    image: ts-dockerhub.lsst.org/scriptqueue:${CYCLE}
    container_name: atqueue
    environment:
      - LSST_DDS_PARTITION_PREFIX=ncsa
      - RUN_ARG=2
      - OSPL_INFOFILE=/tmp/ospl-info-atqueue.log
      - OSPL_ERRORFILE=/tmp/ospl-error-atqueue.log
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.126"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  watcher:
    image: ts-dockerhub.lsst.org/watcher:${CYCLE}
    container_name: watcher
    environment:
      - LSST_DDS_PARTITION_PREFIX=ncsa
      - INDEX=1
      - OSPL_INFOFILE=/tmp/ospl-info-watcher.log
      - OSPL_ERRORFILE=/tmp/ospl-error-watcher.log
    volumes:
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /tmp/docker_tmp/:/tmp/
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.125"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  mtscheduler:
    image: ts-dockerhub.lsst.org/scheduler:${CYCLE}
    container_name: mtscheduler
    environment:
      - LSST_DDS_PARTITION_PREFIX=ncsa
      - INDEX=1
      - OSPL_INFOFILE=/tmp/ospl-info-mtscheduler.log
      - OSPL_ERRORFILE=/tmp/ospl-error-mtscheduler.log
    volumes:
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /tmp/docker_tmp/:/tmp/
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.128"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  atscheduler:
    image: ts-dockerhub.lsst.org/scheduler:${CYCLE}
    container_name: atscheduler
    environment:
      - LSST_DDS_PARTITION_PREFIX=ncsa
      - INDEX=2
      - OSPL_INFOFILE=/tmp/ospl-info-atscheduler.log
      - OSPL_ERRORFILE=/tmp/ospl-error-atscheduler.log
    volumes:
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /tmp/docker_tmp/:/tmp/
    tty: true
    ipc: host
    pid: host
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.129"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
