version: "3.4"

services:

  mtptg:
    image: ts-dockerhub.lsst.org/ptkernel:DM-24828
    container_name: mtptg
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - TELESCOPE=MT
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.131"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  mt-rotator-sim:
    image: lsstts/rotator:v0.4.3
    container_name: mt-rotator-sim
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - RUN_ARG=-s
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.132"

  mt-cam-hexapod-sim:
    image: lsstts/hexapod:v0.5.2
    container_name: mt-cam-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - RUN_ARG=-s 1
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.133"

  mt-m2-hexapod-sim:
    image: lsstts/hexapod:v0.5.2
    container_name: mt-m2-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=ncsa
      - RUN_ARG=-s 2
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.134"

  mtaos:
    image: lsstts/mtaos_sim:w_2020_20_sal
    container_name: mtaos
    environment:
      - LSST_DDS_DOMAIN=ncsa
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.135"

  m1m3:
    image: lsstts/mtm1m3_sim:v1.7.0
    container_name: m1m3
    environment:
      - LSST_DDS_DOMAIN=ncsa
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.136"

  m2:
    image: lsstts/m2:v0.1
    container_name: m2
    environment:
      - LSST_DDS_DOMAIN=ncsa
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.137"

  mtmount:
    image: lsstts/mtmount:v0.1.0
    environment:
      - LSST_DDS_DOMAIN=ncsa
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.138"

networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
