version: "3.4"

services:

  mtptg:
    image: ts-dockerhub.lsst.org/ptkernel:newATMCS_develop
    container_name: mtptg
    environment:
      - LSST_DDS_DOMAIN=comcampath
      - TELESCOPE=Main
    stdin_open: true
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.131"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  mt-rotator-sim:
    image: lsstts/rotator:v0.1.0_sim
    container_name: mt-rotator-sim
    environment:
      - LSST_DDS_DOMAIN=comcampath
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.132"

  mt-cam-hexapod-sim:
    image: lsstts/hexapod:v0.4.0_b42
    container_name: mt-cam-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=comcampath
      - HEXAPOD_ID=-s 1
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.133"

  mt-m2-hexapod-sim:
    image: lsstts/hexapod:v0.4.0_b42
    container_name: mt-m2-hexapod-sim
    environment:
      - LSST_DDS_DOMAIN=comcampath
      - HEXAPOD_ID=-s 2
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.134"

  mtaos:
    image: lsstts/mtaos_sim:w_2020_06_sal
    container_name: mtaos
    environment:
      - LSST_DDS_DOMAIN=comcampath
    volumes:
      - ./mtaos_setup.sh:/home/saluser/.setup.sh
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.135"

  m1m3:
    image: lsstts/mtm1m3_sim
    container_name: m1m3
    environment:
      - LSST_DDS_DOMAIN=comcampath
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.136"

  m2:
    image: lsstts/m2_sim:DM-24028
    container_name: m2
    environment:
      - LSST_DDS_DOMAIN=comcampath
    tty: true
    networks:
      test-stand-network:
        ipv4_address: "141.142.238.137"

networks:
  default:
    external:
      name: test-stand-network
  test-stand-network:
    external: true
