version: '3.6'

services:

    atmcs-sim:
        image: lsstts/at_mcs_sim:0.4_sal3.10_salobj3.12
        container_name: atmcs-sim
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atdome-sim:
        image: lsstts/at_dome_sim:v0.6.1_sal3.10_salobj4
        container_name: atdome-sim
        entrypoint: ["/home/saluser/.setup.sh"]

    atdometrajectory-sim:
        image: lsstts/at_dome_trajectory:v0.8.1
        container_name: atdometrajectory
        entrypoint: ["/home/saluser/.setup.sh"]

    atpneumatics-sim:
        image: lsstts/at_pneumatics_sim:0.2_sal3.10_salobj3.12
        container_name: atpneumatics-sim
        

        entrypoint: ["/home/saluser/.setup.sh"]

    ataos-sim:
        image: lsstts/ataos:v1.1.0
        container_name: ataos
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atptg-sim:
        image: tiagorib/ptkernel:rc0.5_sal3.10
        container_name: atptg

    athexapod-sim:
      image: lsstts/ts_athexapod:v0.2.0
      container_name: athexapod-sim
      depends_on:
        - hexapod-sim

    hexapod-sim:
      image: couger01/hexapod_simulator
      container_name: hexapod-sim
      stdin_open: true
      tty: true

    queue:
      image: lsstts/develop-env:20190610_sal3.10.0_salobj3.12.0
      container_name: queue
      volumes:
        - ./queue_setup.sh:/home/saluser/.setup.sh
      stdin_open: true
      tty: true


    simulation-tests:
      image: lsstts/develop-env:20190705_sal3.10.0_salobj
      container_name: simulation-tests
      ports:
        - "8886:8886"
      stdin_open: true
      tty: true
